# **Dubai Estates Price Prediction** 
<p>in this project we will predict the price of <strong>Dubai</strong> estates based on studing the <strong>2022</strong> transactions.</p>

## ETL (Extract, Transform, Load)

We collect the data from **the Dubai Government Land Department westie**.
- relational data.
- One table.
- csv File.


<a href='https://dubailand.gov.ae/en/'>Dubai Government Land Department webstie Link</a>

In [1]:
import pandas as pd

this data from the data wrangling step in the **Initial Data Exploration**, it's clean.

In [3]:
df = pd.read_csv('data/transactions-2022-12-23.csv')
df.head()

,Transaction Number,Transaction Date,Property ID,Transaction Type,Transaction sub type,Registration type,Is Free Hold?,Usage,Area,Property Type,...,Property Size (sq.m),Room(s),Parking,Nearest Metro,Nearest Mall,Nearest Landmark,No. of Buyer,No. of Seller,Master Project,Project
0,102-1-2022,2022-01-03 07:30:34,1131371499,Sales,Sell - Pre registration,Off-Plan,Free Hold,Residential,DUBAI HARBOUR,Unit,...,119.25,2 B/R,1,NaN,NaN,NaN,1,1,NaN,Beach Mansion
1,102-10-2022,2022-01-03 07:32:56,100227279,Sales,Sell - Pre registration,Off-Plan,Free Hold,Residential,Wadi Al Safa 7,Unit,...,33.44,Studio,1,NaN,NaN,NaN,1,1,NaN,RUKAN
2,102-100-2022,2022-01-03 12:30:23,1147007457,Sales,Sell - Pre registration,Off-Plan,Free Hold,Residential,ARJAN,Unit,...,51.05,1 B/R,1,Sharaf Dg Metro Station,Mall of the Emirates,Motor City,1,1,NaN,SKYZ By Danube
3,102-1000-2022,2022-01-10 13:21:58,1133339823,Sales,Sell - Pre registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,...,36.24,Studio,1,Business Bay Metro Station,Dubai Mall,Downtown Dubai,2,1,NaN,Peninsula One
4,102-10000-2022,2022-04-13 11:21:32,1171598130,Sales,Sell - Pre registration,Off-Plan,Free Hold,Residential,Jumeirah First,Unit,...,118.34,2 B/R,1,NaN,NaN,NaN,1,1,NaN,Port De La Mer - Le Ciel

We will keep the data as csv file in local,the data consist of 23 columns with more than 100000 samples, One Relational Table, there is no transformation to do on it, we tried to upload it to the **IBM Cloud** and work in ibm watson but there is some technical issues, so we will complete the work in the next stages localy.